include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/api/**"
    - "build/**"
    - "script/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
