name: graphql_test_pos
description: graphql_test_pos
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  app_ferry_api:
    path: ./packages/app_ferry_api
  dio: ^4.0.6
  ferry: ^0.11.2+1
  flutter:
    sdk: flutter
  gql: ^0.14.0
  gql_dio_link: ^0.2.3
  gql_exec: ^0.4.1
  gql_link: ^0.5.0
  gql_websocket_link: ^0.3.3
  meta: ^1.8.0
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
