include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/src/*.graphql.dart"
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
