targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - resources/**
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: resources/schema/schema.graphql
              queries_glob: resources/queries/query.graphql
              output: lib/src/api.query.dart
