name: app_ferry_api
description: App artemis api.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  gql_code_builder: ^0.6.0

dev_dependencies:
  ferry_generator: ^0.6.1
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.2
